### ISSUE TITLE
dark mode issue

### ISSUE THREAD

**Issue by itsrafsanjani** [weDevsOfficial/ideabox#1]
When device is in dark mode: 

![image](https://github.com/weDevsOfficial/ideabox/assets/48161278/8d1b7957-fcec-4dc2-a9aa-1d53d1f8c3cd)

**Comment by tareq1988** [comment]
Fixed in https://github.com/weDevsOfficial/ideabox/commit/e5bd9b9556e3c0618062d0fd1cec43d603ea90b7
